### ISSUE TITLE
Unable to install pyminifier in Unix system

### ISSUE THREAD

**Issue by abhishekbhatta** [liftoff/pyminifier#17]
I'm getting the following error which installing pyminifier in my Linux box.

[root@ToolsDB1 pyminifier-2.0]# python --version
Python 2.6.6

[root@ToolsDB1 pyminifier-2.0]# ls -l
total 72
drwxrwxr-x 3 1000 1000  4096 May 25 12:35 docs
-rw-rw-r-- 1 1000 1000 35120 May 24 19:20 LICENSE
-rw-rw-r-- 1 1000 1000  1131 May 25 12:35 PKG-INFO
drwxrwxr-x 2 1000 1000  4096 Oct 20 15:12 pyminifier
drwxrwxr-x 2 1000 1000  4096 May 25 12:35 pyminifier.egg-info
-rw-rw-r-- 1 1000 1000  8792 May 25 12:31 README.rst
-rw-rw-r-- 1 1000 1000   376 May 25 12:35 setup.cfg
-rwxr-xr-x 1 1000 1000  2159 May 24 15:11 setup.py
[root@ToolsDB1 pyminifier-2.0]# python setup.py
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    if sys.version_info.major == 2:
AttributeError: 'tuple' object has no attribute 'major'

Could you please let me know the instillation steps?

**Comment by luto** [comment]
I've got the same problem with python 2.6.6 on CentOS 6.

**Comment by luto** [comment]
I guess [this commit](https://github.com/liftoff/pyminifier/commit/6e3109c0dd5e2865d3af130c26007d7d3ea0f744) fixed it. Can you publish a version containing this to pypi? :)
Thank you, @JohanRensink for the fix! :+1:

**Comment by luto** [comment]
Dang, got the same thing in [analyze.py](https://github.com/liftoff/pyminifier/blob/master/pyminifier/analyze.py#L17).

**Comment by MoshiBin** [comment]
Can we please get the aforementioned commit merged? Python 2.6 has sys.version_info as a tuple, so pyminifier won't work on 2.6 (although it's stated it does in Pypi).

**Comment by MoshiBin** [comment]
+1, can you please push the latest version to pypi?

**Comment by MoshiBin** [comment]
Latest version still has issues with 2.6 - I've sent a PR to fix them.
